/* Generated By:JJTree: Do not edit this line. .\FMParserTreeConstants.java */

package franklinmath.parser;

public interface FMParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTMTLIST = 1;
  public int JJTSTMT = 2;
  public int JJTEXPR = 3;
  public int JJTEXPRMAIN = 4;
  public int JJTTERM = 5;
  public int JJTPOWER = 6;
  public int JJTFACTOR = 7;
  public int JJTIDENTIFIER = 8;
  public int JJTNUMBER = 9;
  public int JJTSTRINGLITERAL = 10;
  public int JJTEQUNLIST = 11;
  public int JJTEQUN = 12;
  public int JJTESCSEQ = 13;
  public int JJTLIST = 14;


  public String[] jjtNodeName = {
    "Program",
    "StmtList",
    "Stmt",
    "Expr",
    "ExprMain",
    "Term",
    "Power",
    "Factor",
    "Identifier",
    "Number",
    "StringLiteral",
    "EqunList",
    "Equn",
    "EscSeq",
    "List",
  };
}
