/* Generated By:JJTree&JavaCC: Do not edit this line. FMParserConstants.java */
package franklinmath.parser;

public interface FMParserConstants {

  int EOF = 0;
  int ID = 4;
  int NUM = 5;
  int NEWLINE = 6;
  int STRING_LITERAL = 7;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "<ID>",
    "<NUM>",
    "<NEWLINE>",
    "<STRING_LITERAL>",
    "\"=\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"==\"",
    "\"\\\\\"",
    "\"{\"",
    "\"}\"",
  };

}
